include: package:pedantic_mono/analysis_options.yaml
# https://pub.dev/packages/pedantic_mono

analyzer:
  strong-mode:
    implicit-dynamic: true
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
