name: KoheiKanagu_github_io
description: Portfolio
homepage: kingu.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.0
  provider: ^4.3.2
  email_validator: ^1.0.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  cloud_firestore_web: ^0.1.1+2
  freezed_annotation: any
  simple_logger: ^1.7.0
  firebase_core: ^0.4.5
  animations: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.3.0
  freezed: ^0.11.5
  build_runner: ^1.10.1
  pedantic_mono: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/