name: KoheiKanagu_github_io
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  provider: ^4.0.2
  firebase: ^7.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
