name: KoheiKanagu_github_io
description: Portfolio
homepage: kingu.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  provider: ^4.1.0-dev
  email_validator: ^1.0.4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  cloud_firestore_web: ^0.1.0+3
  freezed_annotation: ^0.4.0
  simple_logger: ^1.6.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.2.5
  freezed: ^0.5.1
  build_runner: ^1.7.4
  pedantic_mono: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
