name: koheikanagu_github_io
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  cloud_firestore: ^0.16.0+1
  cloud_firestore_web: ^0.3.0+2
  font_awesome_flutter: ^8.11.0
  url_launcher: ^5.7.10
  email_validator: ^1.0.6
  freezed_annotation: any
  animations: ^1.1.2
  json_annotation: any
  hooks_riverpod: ^0.12.4
  gap: ^1.2.0
  logger: ^0.9.4
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  build_runner: any
  pedantic_mono: any
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/