name: koheikanagu_github_io
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  font_awesome_flutter: ^8.11.0
  url_launcher: ^6.0.1
  email_validator: ^2.0.0-nullsafety
  freezed_annotation: any
  animations: ^2.0.0
  json_annotation: any
  hooks_riverpod: ^0.13.0-nullsafety.3
  gap: ^2.0.0-nullsafety.1
  logger: ^1.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  freezed: ^0.13.0-nullsafety.2
  json_serializable: ^4.0.1
  build_runner: any
  pedantic_mono: any
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/