name: GitHub Pages Deploy
on:
  push:
    branches: 
      - develop
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
        channel: 'beta'

    - name: setup
      run: |
        flutter config --enable-web
        flutter pub get
        flutter build web

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.4
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./build/web

    - name: Firebase Deploy
      uses: w9jds/firebase-action@v1.5.0
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
